# Generated by Django 5.0.2 on 2024-02-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_runway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('aircraft_type', models.CharField(max_length=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_destination', to='core.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_origin', to='core.airport')),
            ],
        ),
    ]
