# Generated by Django 5.0.2 on 2024-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_flight_airline_alter_runway_airport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Runway',
            new_name='Runways',
        ),
    ]
